//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.42
//
//     Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGridWebDemo
{


    public partial class Default3
    {
    }
}
